#!/bin/bash


export IP_NAT='62.210.170.243'

export IP_VPS1='212.129.35.183'
export IP_VPS2='212.129.35.184'
export IP_VPS3='212.129.35.185'

export IP_TPPT=${IP_VPS2}
export IP_DTC=${IP_VPS3}
export IP_TUPEUXPASTEST=${IP_TPPT}
export IP_DANSTONCUBE=${IP_DTC}
export IP_FAILOVER=${IP_VPS1}
