#!/bin/bash
FOLDER_ENABLED="init.d/init-enabled"
FOLDER_AVAILABLE="init.d/init-available"
SCRIPT_PREFIX="init-"
VERSION='0.1'
#--------------------------------------

function _get_scripts_path {
  local _result=`echo "$0" | sed -e "s/[^\/]*$//"`
  if [[ $_result = "./" ]]
  then
   _result=`pwd`
  fi
  echo $_result
}
SCRIPTS_PATH=$(_get_scripts_path)
cd $SCRIPTS_PATH

. ./config
. ./functions

encadre "init script v$VERSION"

#--------------------------------------
# usage
#--------------------------------------

function usage {

	jaune "Utilisation: "

	echo -e "init {scriptname} enable \t ${CYAN}Active le script {scriptname}${NORMAL}"
	echo -e "init {scriptname} disable \t ${CYAN}Désactive le script {scriptname}${NORMAL}"
	echo -e "init {scriptname} show \t\t ${CYAN}Affiche le script {scriptname}${NORMAL}"
	echo -e "init {scriptname} edit \t\t ${CYAN}Edite le script {scriptname}${NORMAL}"
	echo -e "init start \t\t\t ${CYAN}Lance les scripts actifs avec la paramètre start${NORMAL}"
	echo -e "init stop \t\t\t ${CYAN}Lance les scripts actifs avec le paramètre stop${NORMAL}"
	echo -e "init scripts \t\t\t ${CYAN}Affiche les scripts actifs${NORMAL}"
}

#--------------------------------------
# commande_*
#--------------------------------------

function commande_scripts {

	jaune "Scripts actifs: "

	for script in ${SCRIPTS_PATH}/${FOLDER_ENABLED}/*; do
        	rouge "(*) ${script}" | sed -e "s,${SCRIPTS_PATH}/${FOLDER_ENABLED}/,,g"
	done;
}

function commande_start {

	jaune "Lancement des scripts..."

	for script in ${SCRIPTS_PATH}/${FOLDER_ENABLED}/*; do
  	rouge "-> ${script}" | sed -e "s,${SCRIPTS_PATH}/${FOLDER_ENABLED}/,,g"
  	chmod +x ${script}
  	commande "${script} start"
	done;
}

function commande_stop {

	jaune "Arrêt des services..."

	for script in ${SCRIPTS_PATH}/${FOLDER_ENABLED}/*; do
    rouge "-> ${script}" | sed -e "s,${SCRIPTS_PATH}/${FOLDER_ENABLED}/,,g"
    chmod +x ${script}
    commande "${script} stop"
  done;
}

#--------------------------------------
# commande_scriptname_*
#--------------------------------------

function commande_scriptname_enable {
    if [[ ! -d $SCRIPTS_PATH/$FOLDER_ENABLED ]]
    then
      commande "mkdir $SCRIPTS_PATH/$FOLDER_ENABLED"
    fi
    fn_command_script_enable $SCRIPTS_PATH $FOLDER_AVAILABLE $FOLDER_ENABLED "${SCRIPT_PREFIX}$1"
}

function commande_scriptname_disable {
    fn_command_script_disable $SCRIPTS_PATH $FOLDER_AVAILABLE $FOLDER_ENABLED "${SCRIPT_PREFIX}$1"
}

function commande_scriptname_edit {
  	fn_command_script_edit $SCRIPTS_PATH $FOLDER_AVAILABLE $FOLDER_ENABLED "${SCRIPT_PREFIX}$1"
}

function commande_scriptname_show {
  	fn_command_script_show $SCRIPTS_PATH $FOLDER_AVAILABLE $FOLDER_ENABLED "${SCRIPT_PREFIX}$1"
}

#--------------------------------------
# parse_*
#--------------------------------------

function parse_commande_scriptname {

	case $2 in
	"enable")
		commande_scriptname_enable $1
  	;;
	"disable")
		commande_scriptname_disable $1
  	;;
	"show")
		commande_scriptname_edit $1
  	;;
	"edit")
		commande_scriptname_edit $1
  	;;
	*)
		if [[ ! -z $2 ]]
		then
			rouge "Commande inconnue: $2"
		fi
  	usage
		;;
	esac
}

function parse_commande {
	case $1 in
	"scripts")
		commande_scripts
		;;
	"start")
		commande_start
		;;
	"stop")
		commande_stop
		;;
	*)
		parse_commande_scriptname $1 $2
		;;
	esac
}

#--------------------------------------
# MAIN !
#--------------------------------------

parse_commande $1 $2
