#!/bin/bash

# TODO !
# pour chaque script dans init-enabled/ lancer le script avec les parametres LSB standards si disponibles


#------------------------------------------------------------------------
#------------------------------------------------------------------------
#------------------------------------------------------------------------


SCRIPTS_PATH="/root/my-proxmox-scripts"
FOLDER_ENABLED="init.d/init-enabled"
FOLDER_AVAILABLE="init.d/init-available"
SCRIPT_PREFIX="init-"

VERSION=0.1


cd $SCRIPTS_PATH

. ./config
. ./functions

encadre "INIT SCRIPT V$VERSION"


function list_enabled_scripts {

	jaune "Scripts actifs: "

	for script in ${SCRIPTS_PATH}/${FOLDER_ENABLED}/*; do
        	rouge "(*) ${script}" | sed -e "s,${SCRIPTS_PATH}/${FOLDER_ENABLED}/,,g"
	done;
}




#------------------------------------------------------------------------
#------------------------------------------------------------------------
#------------------------------------------------------------------------

function show_scripts {
	list_enabled_scripts
}


function start_scripts {

	jaune "Lancement des scripts..."

	for script in ${SCRIPTS_PATH}/${FOLDER_ENABLED}/*; do
        	rouge "-> ${script}" | sed -e "s,${SCRIPTS_PATH}/${FOLDER_ENABLED}/,,g"
        	chmod +x ${script}
        	commande "${script} start"
	done;
}


function stop_scripts {

	jaune "Arrêt des services..."

	for script in ${SCRIPTS_PATH}/${FOLDER_ENABLED}/*; do
                rouge "-> ${script}" | sed -e "s,${SCRIPTS_PATH}/${FOLDER_ENABLED}/,,g"
                chmod +x ${script}
                commande "${script} stop"
        done;
}

function command_script {

	case $2 in
	"enable")
		if [[ ! -d $SCRIPTS_PATH/$FOLDER_ENABLED ]]
		then
			commande "mkdir $SCRIPTS_PATH/$FOLDER_ENABLED"
		fi
		command_script_enable $SCRIPTS_PATH $FOLDER_AVAILABLE $FOLDER_ENABLED "${SCRIPT_PREFIX}$1"
        	;;
	"disable")
		command_script_disable $SCRIPTS_PATH $FOLDER_AVAILABLE $FOLDER_ENABLED "${SCRIPT_PREFIX}$1"
        	;;
	*)
		if [[ ! -z $2 ]]
		then
			rouge "Commande inconnue: $2"
		fi
        	jaune "Utilisation: "
        	echo -e "init {scriptname} enable \t ${CYAN}Active le script {scriptname}${NORMAL}"
        	echo -e "init {scriptname} disable \t ${CYAN}Désactive le script {scriptname}${NORMAL}"
        	echo -e "init start \t\t\t ${CYAN}Lance les scripts actifs avec la paramètre start${NORMAL}"
        	echo -e "init stop \t\t\t ${CYAN}Lance les scripts actifs avec le paramètre stop${NORMAL}"
		echo -e "init scripts \t\t\t ${CYAN}Affiche les scripts actifs${NORMAL}"
        	;;
	esac

}

case $1 in
"scripts")
	show_scripts
	;;
"start")
	start_scripts
	;;
"stop")
	stop_scripts
	;;
*)
	command_script $1 $2
	;;
esac
