#!/bin/bash

. ./functions


# Dossiers de scripts par défaut si les variables ne sont pas fournies par un script externe !

if [[ -z "${DEFAULT_FOLDER}" ]]
then
	DEFAULT_FOLDER="scripts"
fi

if [[ -z "${DEFAULT_PATH}" ]]
then
	DEFAULT_PATH="/root/scripts/scripts.d"
fi


barre
echo -e  "${JAUNE}[DIS SCRIPT]${NORMAL} - ${ROSE}${DEFAULT_PATH}/${DIR_AVAILABLE}${NORMAL}"
barre


SCRIPTS_PATH=${DEFAULT_PATH}
SCRIPTS_FOLDERS_NAME=${DEFAULT_FOLDER}


DIR_AVAILABLE="${SCRIPTS_FOLDERS_NAME}-available"       # fichiers configurés
DIR_ENABLED="${SCRIPTS_FOLDERS_NAME}-enabled"           # fichiers activés


if [[ -d "${SCRIPTS_PATH}" ]]
then
	mkdir -p "${SCRIPTS_PATH}/${SCRIPTS_FOLDERS_NAME}-available"
	mkdir -p "${SCRIPTS_PATH}/${SCRIPTS_FOLDERS_NAME}-enabled"
fi



# Quel script ?
if [ -z ${1} ]; then

	NB_SCRIPTS=$(ls -A1 ${SCRIPTS_PATH}/${DIR_ENABLED}/* 2>/dev/null | wc -l)

	if [ "$NB_SCRIPTS" -lt 1 ]
	then
		jaune "${ROUGE}Pas de scripts disponibles dans le dossier ${JAUNE}${SCRIPTS_PATH}/${DIR_ENABLED}${NORMAL}"
		exit 1
	fi

        echo "Quel script voulez vous désactiver ?"

        echo "Liste des scripts actifs: "

        for site in ${SCRIPTS_PATH}/${DIR_ENABLED}/*; do
		if [[ -f $site ]]
		then
                	echo -e "(${ROUGE}*${NORMAL})${CYAN}${site}${NORMAL}" | sed -e "s,${SCRIPTS_PATH}/${DIR_ENABLED}/,,g"
		fi
        done;

	echo -n "Nom du script ? "

	read SITENAME

else
        SITENAME=${1}
fi


# Déjà désactivé ?
if ! [ -e ${SCRIPTS_PATH}/${DIR_ENABLED}/${SITENAME} ]; then
        jaune "Ce script est déjà désactivé ! ! !"
        exit 1
fi


# Traitement :
if ! rm ${SCRIPTS_PATH}/${DIR_ENABLED}/${SITENAME} 2>/dev/null; then
        rm -f ${SCRIPTS_PATH}/${DIR_ENABLED}/${PRIORITY}-${SITENAME}
fi

