#!/bin/bash
DATE=$(date)
LOG_PATH="/root/logs"
LOG_FILE="init-sample.log"

#fout la date a la suite du fichier /root/logs/init-sample.log

LOG="${LOG_PATH}/${LOG_FILE}"
case $1 in
"start")
	echo "Démarrage à ${DATE}" >> ${LOG_FILE}
	;;
"stop")
	echo "Arrêt à ${DATE}" >> ${LOG_FILE}
	;;
*)
	echo "Lancement sans argument à ${DATE}" >> ${LOG_FILE}
	;;
esac
