#!/bin/bash
DATE=$(date)
SCRIPTS_PATH="/root/scripts"
LOG_PATH="/root/logs"
LOG_FILE="init-rezo.log"

LOG="${LOG_PATH}/${LOG_FILE}"
case $1 in
"start", "restart")
	echo "Exécution du script rezo à ${DATE}" > ${LOG_FILE}
  $SCRIPTS_PATH/rezo apply >> ${LOG_FILE}
	;;
*)
	echo "Lancement avec argument non géré $1 à ${DATE}" >> ${LOG_FILE}
	;;
esac
