#!/bin/bash

#mikoscripts init sample
#fout la date a la suite du fichier /root/logs/init-sample.log

DATE=$(date)
LOGFILE="/root/logs/init-sample.log"

cd /root/scripts/
echo "Le systeme à booté à ${DATE}" >> ${LOGFILE}
